<% require 'uri' %>

development:
  database: mes_courses
  capsize: <%= 10.megabytes %>
  host: localhost
  port: 27017

test:
  <<: *development

<% ENV['MONGOHQ_URL'] ||= "http://localhost:27017" %>
production:
  database: mes_courses
  capsize: <%= 10.megabytes %>
  host: <%= URI.parse(ENV['MONGOHQ_URL']).host %>
  port: <%= URI.parse(ENV['MONGOHQ_URL']).port %>
  user: <%= URI.parse(ENV['MONGOHQ_URL']).user %>
  password: <%= URI.parse(ENV['MONGOHQ_URL']).password %>

cucumber:
  <<: *test