<% require 'uri' %>

development: &development
  host: localhost
  port: 27017
  database: mes_courses
  capsize: <%= 100.megabytes %>

test: &test
  <<: *development

<% ENV['MONGOHQ_URL'] ||= "http://localhost:27017/mes-courses" %>
production:
  host: <%= URI.parse(ENV['MONGOHQ_URL']).host %>
  port: <%= URI.parse(ENV['MONGOHQ_URL']).port %>
  database: <%= URI.parse(ENV['MONGOHQ_URL']).path[1..-1] %>
  username: <%= URI.parse(ENV['MONGOHQ_URL']).user %>
  password: <%= URI.parse(ENV['MONGOHQ_URL']).password %>
  capsize: <%= 15.megabytes %>

cucumber:
  <<: *test
