development:
  adapter: postgresql
  database: mes_courses_development
  encoding: utf8
  pool: 5
  timeout: 5000
  username: mes_courses
  password: password
  host: localhost
  port: 5433

test:
  adapter: postgresql
  database: mes_courses_test
  encoding: utf8
  pool: 5
  timeout: 5000
  username: mes_courses
  password: password
  host: localhost
  port: 5433

# remove when we have a segregated host to run the ci
ci:
  adapter: postgresql
  database: mes_courses_ci
  encoding: utf8
  pool: 5
  timeout: 5000
  username: mes_courses
  password: password
  host: localhost
  port: 5433

production:
  adapter: postgresql
  database: mes_courses_production
  encoding: utf8
  pool: 5
  timeout: 5000
  username: mes_courses
  password: password
  host: localhost
  port: 5433

