development:
  adapter: postgresql
  database: mes_courses_development
  encoding: utf8
  pool: 5
  timeout: 5000
  username: philou

test: &test
  adapter: sqlite3
  database: ":memory:"

cucumber:
  adapter: postgresql
  database: mes_courses_cucumber
  encoding: utf8
  pool: 5
  timeout: 5000
  username: philou

ci:
  adapter: postgresql
  database: mes_courses_ci
  encoding: utf8
  pool: 5
  timeout: 5000
  username: philou

production:
  adapter: postgresql
  database: mes_courses_production
  encoding: utf8
  pool: 5
  timeout: 5000
  username: philou

